version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert/:/cert/
      - ./.htpasswd:/auth/.htpasswd
    ports:
      - 80:80
      - 443:443
    links:
      - web:web

  web:
    image: tutum/hello-world
    expose:
      - "80"

